name: seedart
description: A headless Flutter-powered CLI animation engine
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_platform_interface: ^5.1.0  # Platform-agnostic FFmpeg interface
  path: ^1.8.3
  image: ^4.1.3  # For image processing and file saving

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
